# Generated by Django 6.0.4 on 2026-05-02 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='BookingDate',
            field=models.DateField(default=datetime.datetime(2026, 5, 2, 4, 11, 30, 820572, tzinfo=datetime.timezone.utc)),
        ),
    ]
