# Generated by Django 6.0.4 on 2026-05-02 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='BookingDate',
            field=models.DateField(default=datetime.datetime(2026, 5, 2, 4, 41, 4, 166342, tzinfo=datetime.timezone.utc)),
        ),
    ]
