# Generated by Django 6.0.4 on 2026-05-02 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='BookingDate',
            field=models.DateField(default=datetime.datetime(2026, 5, 2, 18, 45, 22, 807901, tzinfo=datetime.timezone.utc)),
        ),
    ]
